....................................................................     [100%]
============================== warnings summary ===============================
tests/test_full_suite.py::TestDiscoveryManager::test_source_discovery
  D:\GitHub\CleanConfigs-SubMerger-\src\streamline_vpn\discovery\manager.py:444: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
    async with session.get(
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_full_suite.py::TestDiscoveryManager::test_source_discovery
  D:\GitHub\CleanConfigs-SubMerger-\src\streamline_vpn\discovery\manager.py:122: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
    async with session.get(
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_full_suite.py::TestDiscoveryManager::test_source_discovery
  D:\GitHub\CleanConfigs-SubMerger-\src\streamline_vpn\discovery\manager.py:187: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
    async with session.get(
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_full_suite.py::TestDiscoveryManager::test_source_discovery
  D:\GitHub\CleanConfigs-SubMerger-\src\streamline_vpn\discovery\manager.py:285: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
    async with session.get(
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_full_suite.py::TestDiscoveryManager::test_source_discovery
  D:\GitHub\CleanConfigs-SubMerger-\src\streamline_vpn\discovery\manager.py:334: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
    async with session.get(
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_full_suite.py::TestDiscoveryManager::test_source_discovery
  D:\GitHub\CleanConfigs-SubMerger-\src\streamline_vpn\discovery\manager.py:397: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
    async with session.head(
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
68 passed, 6 warnings in 3.14s
